# Generated by Django 3.0.4 on 2020-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200420_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipedataprocessed',
            options={'ordering': ['-site_time']},
        ),
        migrations.AlterField(
            model_name='pipedataprocessed',
            name='timestamp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pipedataprocessed',
            unique_together={('machine_id', 'site_time')},
        ),
    ]
