# Generated by Django 3.0.4 on 2020-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201111_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('current_dt', models.DateTimeField()),
            ],
        ),
    ]
