# Generated by Django 3.0.4 on 2020-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201127_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSearchTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='test', max_length=250, null=True)),
                ('machine_id', models.CharField(blank=True, default='test', max_length=100, null=True)),
                ('last_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
