# Generated by Django 3.0.4 on 2020-12-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_machinelocalserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedataprocessed',
            name='site_local_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
