# Generated by Django 3.0.4 on 2021-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pipedataprocessed_site_local_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_total_shift',
            field=models.IntegerField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
