# Generated by Django 3.0.4 on 2021-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210104_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='mfd_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
