# Generated by Django 3.0.4 on 2021-01-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_code_mfd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='company_name',
            field=models.CharField(default='Supreme', max_length=200),
        ),
        migrations.AddField(
            model_name='code',
            name='product_detail',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='shift',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='shift_engineer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='mfd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
