# Generated by Django 3.0.4 on 2021-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210107_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='standard_CML_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
