# Generated by Django 3.0.4 on 2021-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_machinetimezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipePassStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pipe_pass_status_code', models.IntegerField(unique=True)),
                ('pipe_pass_status', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pipe Pass Status',
            },
        ),
        migrations.AlterModelOptions(
            name='machinetimezone',
            options={'verbose_name_plural': 'Machine Time Zone'},
        ),
    ]
