# Generated by Django 3.0.4 on 2021-03-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210308_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipedataprocessed',
            name='site_local_time',
        ),
    ]
