# Generated by Django 3.0.4 on 2021-03-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_pipedataprocessed_site_local_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipedataprocessed',
            options={'ordering': ['-site_local_time']},
        ),
        migrations.AlterUniqueTogether(
            name='pipedataprocessed',
            unique_together={('machine_id', 'site_local_time')},
        ),
    ]
