# Generated by Django 3.0.4 on 2021-03-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210309_1128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pipedataprocessed',
            unique_together={('machine_id', 'site_time')},
        ),
    ]
