# Generated by Django 3.0.4 on 2021-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210326_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedpipebyqc',
            name='machine_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rejectedpipebyqc',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='rejectedpipebyqc',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rejectedpipebyqc',
            name='user',
        ),
    ]
